name: fwupd
version: 0.1.0

description:
  Provides a client to connect to fwupd - the service that does firmware updates on Linux.

homepage: https://github.com/canonical/fwupd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  dbus: ^0.6.2
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
  test_cov: ^1.0.1

