name: fwupd
version: 0.0.2

description:
  Provides a client to connect to fwupd - the service that does firmware updates on Linux.

homepage: https://github.com/canonical/fwupd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dbus: ^0.5.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8
