name: fwupd
version: 0.2.2

description:
  Provides a client to connect to fwupd - the service that does firmware updates on Linux.

homepage: https://github.com/canonical/fwupd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  dbus: ^0.7.8
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
